site_name: AI Agent Engineer Course
site_description: "Master AI agent engineering with hands-on projects. Learn to build, deploy, and scale intelligent AI agents, multi-agent systems, and autonomous workflows. Free, open-source curriculum."
site_author: "Karthik K Pro and contributors"
site_url: https://karthikkpro.github.io/ai-agent-engineer-course/
repo_url: https://github.com/karthikkpro/ai-agent-engineer-course
repo_name: karthikkpro/ai-agent-engineer-course
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/theme.css

extra_javascript:
  - https://unpkg.com/@structured-data/schema-dot-org@1.0.0/dist/schema-dot-org.min.js

nav:
  - "🏠 Home": index.md
  - "🗺️ Roadmap": Roadmap.md
  - "📚 Course":
      - "🎯 Phase 0 - Foundations":
          - "0-1 Why AI Agents": phase-0/lesson-1.md
          - "0-2 Core Concepts": phase-0/lesson-2.md
          - "0-3 Thinking Like an Agent": phase-0/lesson-3.md
      - "🛠️ Phase 1 - Essential Tools":
          - "1-1 Python for Agents": phase-1/lesson-1.md
          - "1-2 Prompt Engineering": phase-1/lesson-2.md
          - "1-3 Tool Wrappers & LangChain": phase-1/lesson-3.md
          - "1-4 Memory & Basic RAG": phase-1/lesson-4.md
          - "1-5 Model APIs": phase-1/lesson-5.md
      - "🔄 Phase 2 - Agentic Workflows":
          - "2-1 Agent Loop Deep Dive": phase-2/lesson-1.md
          - "2-2 Prompt & Tool Chaining": phase-2/lesson-2.md
          - "2-3 Hybrid RAG & Context": phase-2/lesson-3.md
          - "2-4 Evaluation & Tracing": phase-2/lesson-4.md
      - "🤖 Phase 3 - Multi-Agent":
          - "3-1 Multi-Agent Orchestration": phase-3/lesson-1.md
          - "3-2 Advanced RAG Pipelines": phase-3/lesson-2.md
          - "3-3 State & DAG Orchestration": phase-3/lesson-3.md
          - "3-4 Collaboration Patterns": phase-3/lesson-4.md
          - "3-5 Framework Survey": phase-3/lesson-5.md
      - "🚀 Phase 4 - Production":
          - "4-1 Production Deployment": phase-4/lesson-1.md
          - "4-2 Containerization & Serverless": phase-4/lesson-2.md
          - "4-3 CI/CD & Secrets": phase-4/lesson-3.md
          - "4-4 Observability & Incidents": phase-4/lesson-4.md
          - "4-5 Security & Compliance": phase-4/lesson-5.md
      - "🛡️ Phase 5 - Safety & RLHF":
          - "5-1 Advanced Safety": phase-5/lesson-1.md
          - "5-2 Guardrails Engineering": phase-5/lesson-2.md
          - "5-3 RLHF & Policy Tuning": phase-5/lesson-3.md
          - "5-4 Continuous Evaluation": phase-5/lesson-4.md
      - "🏆 Phase 6 - Portfolio":
          - "6-1 Portfolio Leadership": phase-6/lesson-1.md
          - "6-2 Capstone Showcase": phase-6/lesson-2.md
          - "6-3 Open Source & Community": phase-6/lesson-3.md
          - "6-4 Lifelong Learning Loop": phase-6/lesson-4.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karthikkpro/ai-agent-engineer-course
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/karthikkpro
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/karthikkpro
      name: LinkedIn

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  version:
    provider: mike

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
